#!/usr/bin/env bash
# Shiva keyframes at gigantic scale. Refs: ref/shiva_giant.png (scale + physique), ref/shiva.png (face), ref/climber_hands.png, ref/cliff.png
cd "$(dirname "$0")/.."
C="The climber is exactly as in the hands reference: medium-brown human hands with natural proportions, mustard wool garment with identical ribbed mustard cuffs, thin red thread on his LEFT wrist (LEFT side of frame), exactly two rudraksha strands on his RIGHT wrist (RIGHT side of frame). No gloves."
S="Lord Shiva is the gigantic, heavily muscular mythological figure from the giant reference image, about three times a man's height, with exactly the same calm compassionate face as the face reference: broad shoulders, defined chest and abs, thick arms, enormous strong hands (one hand larger than the climber's whole forearm), matte ash-blue skin with pores and ash texture, matted jata topknot with a small crescent, white tripundra, rudraksha, grey cobra, tiger-stripe cloth, natural brown eyes with no glow. The trident is always in his LEFT hand."
L="Location as in the cliff reference: icy granite cliff, narrow snow-covered rock ledge, snowstorm at dusk. Photoreal cinematic film still, natural skin detail, realistic scale and contact shadows, snowflakes at varied depths, 9:16. No text, no glow effects, no sparks."
R="ref/shiva_giant.png ref/shiva.png ref/climber_hands.png ref/cliff.png"
g(){ python3 tools/img.py "kf/$1.png" "$2" $R > "kf/$1.log" 2>&1 & }
g K3a "First-person POV looking straight up from just below the snow-covered ledge. $C His LEFT hand (left side of frame) reaches up desperately. Above the ledge, the gigantic Shiva leans over the edge, his huge face and massive shoulders filling the upper part of the frame, and his enormous RIGHT hand descends from the top-left, open, just about to close around the climber's small left wrist. The scale difference is dramatic. $S $L"
g K3b "Close first-person POV looking up: the enormous ash-blue RIGHT hand of the gigantic Shiva, coming from the top-left, completely wraps around the climber's LEFT wrist and lower forearm just above the mustard cuff — his huge fingers encircle it easily, thumb on the inside, the climber's skin and the red thread pressed under the grip, the climber's small hand dangling below the giant fist. Anatomically clear, five fingers on each hand. Above, Shiva's massive muscular forearm with a rudraksha band and the snowy ledge edge. $C $S $L"
g K4a "First-person POV looking up while being lifted: the gigantic Shiva stands on the snowy ledge and lifts the climber up past the ledge edge with one arm, his enormous RIGHT hand gripping the climber's LEFT wrist (left side of frame), his huge bicep and shoulder flexed under the load; his LEFT hand holds the towering trident planted in the snow (right side of frame). His calm face looks down from high above. The climber's RIGHT hand (right side, two rudraksha strands) reaches toward the ledge. $C $S $L"
wait
g K4b "First-person POV at ledge level as the climber hauls himself onto the snow-covered ledge: his RIGHT hand (right side of frame, two rudraksha strands) planted flat in the packed snow, his knee in dark trousers coming onto the rock at the bottom edge, his LEFT wrist (left side, red thread) still held by the enormous RIGHT hand of the gigantic Shiva, who crouches in front: his massive knee, thigh and tiger-stripe cloth fill the frame, his huge muscular torso and face rising above. The trident in his LEFT hand. $C $S $L"
g K5 "First-person POV of the climber kneeling safely on the snowy ledge, looking up at the gigantic Shiva who crouches in front of him: his huge calm, reassuring face and massive muscular shoulders fill the upper frame, wind moving strands of his matted hair. At the bottom-left of frame his enormous RIGHT hand still loosely holds the climber's small LEFT wrist (mustard cuff, red thread). The towering trident in his LEFT hand at the right edge. $C $S $L"
g K6 "First-person POV of the climber kneeling on the snowy ledge: in the lower foreground his two hands are pressed together in namaste (identical mustard cuffs, red thread on the LEFT wrist on the left side, two rudraksha strands on the RIGHT wrist on the right side). In front of him on the same ledge the gigantic, heavily muscular Shiva stands towering, seen from the knees up, filling the frame height, looking down with a gentle expression, his enormous RIGHT hand (left side of frame) raised in blessing, the towering trident in his LEFT hand. Behind him the storm is softening and the pyramid snow peak emerges through thinning cloud in soft warm light. $C $S $L"
wait
grep -L saved kf/K3a.log kf/K3b.log kf/K4a.log kf/K4b.log kf/K5.log kf/K6.log; echo done
