#!/usr/bin/env bash
# Boundary keyframes. Refs: ref/climber_hands.png (hands/garment), ref/shiva.png (performer), ref/cliff.png (location).
cd "$(dirname "$0")/.."
C="The climber is exactly as in the hands reference: adult South Asian man, medium-brown hands with natural proportions and short nails, mustard-yellow wool outer garment with identical ribbed mustard cuffs, a thin red thread on his LEFT wrist (which appears on the LEFT side of the frame in first person), exactly two rudraksha strands on his RIGHT wrist (RIGHT side of the frame). No gloves."
S="Shiva is the same live performer as in the Shiva reference: same face, calm compassionate expression, natural proportions, matte ash-blue body paint with visible pores and ash texture, matted jata topknot with a small crescent, white tripundra, rudraksha necklaces and armbands, a grey cobra around the neck, tiger-stripe waist cloth, natural brown eyes (no glow). The trident is always in his LEFT hand."
L="Location as in the cliff reference: steep icy granite cliff, narrow snow-covered rock ledge, snowstorm at dusk, cold blue-grey light. Photoreal live-action film still shot on a cinema camera, natural skin detail, snowflakes at varied depths and focus, 9:16. No text, no glow effects."
g(){ python3 tools/img.py "kf/$1.png" "$2" "${@:3}" > "kf/$1.log" 2>&1 & }
g KA0 "First-person POV pressed close to an icy rock face. $C His LEFT hand (left side of frame) is jammed into a vertical crack in the rock at upper-left; the thin crust of ice under those fingers is visibly fracturing, small ice chips flaking off. His RIGHT hand grips a small hold lower on the right. Mustard cuffs and the red thread clearly visible. Glimpse of the drop and blowing snow at the bottom edge. $L" ref/climber_hands.png ref/cliff.png
g KB0 "First-person POV looking down along his own body on a steep icy cliff. $C His brown leather mountaineering boot stands on a narrow icy rock foothold that is cracking apart, ice chunks starting to fall into the void below. His LEFT hand (left side of frame, mustard cuff, red thread) grips a rock knob at mid-left. Vertiginous drop into blowing snow beneath. $L" ref/climber_hands.png ref/cliff.png
wait
g K2 "First-person POV looking straight up while hanging just below a snow-covered rock ledge after a short fall. $C His LEFT hand (left side of frame) stretches up desperately toward the overhanging edge of the ledge about an arm's length out of reach; his RIGHT hand (right side) claws at the icy rock face. Snowflakes streak past, some close to the lens. The ledge edge and dark storm sky above. $L" ref/climber_hands.png ref/cliff.png
g K3a "First-person POV looking straight up at the edge of a snow-covered rock ledge. $C His LEFT hand (left side of frame) reaches up. From the ledge above, Shiva's RIGHT arm extends down from the top-left of the frame, his open RIGHT hand just a few centimetres above the climber's left wrist, about to grab it; above the edge we glimpse Shiva's shoulder and the side of his face looking down. $S $L" ref/climber_hands.png ref/shiva.png ref/cliff.png
wait
g K3b "Close first-person POV looking up: Shiva's RIGHT hand (ash-blue, entering from the top-left) firmly grips the climber's LEFT wrist (left side of frame) just above the mustard cuff: fingers wrapped fully around the wrist, thumb on the inside, skin compressed under the grip, the red thread pushed slightly by his fingers, tendons tense in both forearms. Anatomically clear, each hand has five fingers. Above, the snowy ledge edge and Shiva's rudraksha armband. $C $S $L" ref/climber_hands.png ref/shiva.png ref/cliff.png
g K4a "First-person POV looking up from just below the ledge: Shiva kneels at the very edge of the snow-covered ledge and leans over, his RIGHT hand firmly gripping the climber's LEFT wrist (left side of frame), his elbow bent and shoulder loaded with effort as he pulls; his LEFT hand holds the trident planted upright in the snow on the right of the frame. His calm face looks down into the lens. The climber's RIGHT hand (right side, two rudraksha strands) reaches for the ledge edge. $C $S $L" ref/climber_hands.png ref/shiva.png ref/cliff.png
wait
g K4b "First-person POV now at ledge level, the climber hauling himself onto the snow-covered ledge: his RIGHT hand (right side of frame, two rudraksha strands, mustard cuff) is planted flat in the packed snow on the ledge, his knee in dark trousers is coming up onto the rock at the bottom edge of the frame, his LEFT wrist (left side, red thread) is still held firmly by Shiva's RIGHT hand. Shiva kneels just in front, upper body and lower face visible, trident in his LEFT hand. Contact shadows in the snow. $C $S $L" ref/climber_hands.png ref/shiva.png ref/cliff.png
g K5 "First-person POV of the climber kneeling safely on the snowy ledge, looking at Shiva who kneels close in front of him: medium close-up of the same face, calm and reassuring, wind moving individual strands of his matted hair and the cloth, snow on his shoulders. At the bottom-left of frame Shiva's RIGHT hand still holds the climber's LEFT wrist (mustard cuff, red thread). The trident stands in his LEFT hand at the right edge. $C $S $L" ref/climber_hands.png ref/shiva.png ref/cliff.png
wait
g K6 "First-person POV of the climber kneeling on the snowy ledge: in the lower foreground his two hands are pressed together in a namaste of gratitude (mustard cuffs on both wrists, red thread on the LEFT wrist, two rudraksha strands on the RIGHT wrist). In front of him Shiva stands on the ledge, his RIGHT hand raised gently in a blessing gesture, the trident in his LEFT hand. Behind them the storm is softening and through clearing cloud the pyramid snow peak from the location reference begins to appear in soft warm light. $C $S $L" ref/climber_hands.png ref/shiva.png ref/cliff.png
wait
grep -L saved kf/*.log; echo done
