#!/usr/bin/env bash
# One Veo shot per action. Usage: shots.sh [ids...]
cd "$(dirname "$0")/.."
REAL="Photoreal live-action devotional film, handheld cinema camera with physically coherent body-driven movement and weight, natural skin detail, snowflakes at varied depths and focus, cloth and beads reacting to motion and wind. Climber continuity: mustard wool garment with identical ribbed cuffs, thin red thread on the LEFT wrist (left side of frame), exactly two rudraksha strands on the RIGHT wrist (right side of frame), five fingers per hand. Shiva continuity: the gigantic mythological figure from the first frame, about three times a man's height, heavily muscular and well built, exactly the same calm face as in the first frame, matte ash-blue skin with pores and ash texture, natural brown eyes with no glow, trident only in his LEFT hand; his huge hands move with real weight and natural anatomy. No music, no speech, no text."
CL="Photoreal live-action film, strictly first-person POV from the climber's own eyes for the entire shot: the camera never leaves his head, we never see his face, back or body from outside, and no other person appears. Handheld body-driven camera movement with real weight, natural medium-brown skin, snowflakes at varied depths and focus. His hands stay medium-brown human skin the whole time; mustard wool garment with identical ribbed cuffs; thin red thread on the LEFT wrist (left side of frame); exactly two rudraksha strands on the RIGHT wrist (right side of frame); five fingers per hand. No music, no speech, no text."
declare -A F L T
F[A]=kf/KA0.png; T[A]="First-person POV. The LEFT hand's fingers are jammed in an icy crack; the ice crust under them fractures and breaks away with a sharp crack, the fingers scrape and slip out, the camera drops abruptly with the body; the RIGHT hand lunges for a hold and misses by centimetres; he falls back a short distance down the steep face, the rock rushing upward past the lens, then he slams against the slope and slides, snow spraying. One continuous readable fall. Audio: wind, sharp ice crack, fingernails scraping rock, a gasp, the body thudding and sliding on ice. $CL"
F[B]=kf/KB0.png; T[B]="First-person POV looking down. The narrow icy foothold under his boot cracks and breaks away; chunks of ice fall into the void, his leg drops, the camera jolts down with his whole body weight; his LEFT hand is torn off its rock knob, his RIGHT hand grabs and misses, and he falls a short distance down the steep face, rock rushing upward past the lens, then slams against the slope and slides. One continuous readable fall. Audio: wind, ice cracking, falling ice clatter, boot scraping, a sharp gasp, body hitting and sliding on ice. $CL"
F[C]=kf/K2.png; T[C]="First-person POV looking up, hanging and slipping just below the snowy ledge. A gust throws snow across the lens, briefly obscuring the view, then it clears; his LEFT hand stretches and strains upward toward the ledge edge, trembling, fingers spread, slipping a little lower; his RIGHT hand claws at the ice for grip. Strained, ragged breathing. Audio: howling wind, snow hitting the lens, strained breath, ice crumbling under fingers. $CL"
F[D]=kf/K3a.png; L[D]=kf/K3b.png; T[D]="First-person POV looking up at the ledge. The gigantic Shiva's enormous RIGHT hand comes down from above and closes firmly around the climber's LEFT forearm just above the mustard cuff: the huge fingers wrap fully around the forearm, the skin compresses, the red thread is pressed. Throughout the entire shot the climber's own LEFT hand remains clearly visible ABOVE the grip, open with five tense spread fingers, attached to the same forearm; it never disappears, never merges into the sleeve and is never covered. The fall stops with one short jolt of the body and camera, then the grip holds steady. No sparks, no glow. Audio: a solid slap of skin catching the wrist, a sharp intake of breath, wind, garment creak. $REAL"
F[E]=kf/K4a.png; L[E]=kf/K4b.png; T[E]="First-person POV. The gigantic, muscular Shiva lifts the climber up with one arm in a steady powerful motion: his elbow bends, his huge bicep and shoulder flex under the load, the connected wrist grip never breaks. The camera rises steadily up the rock face to ledge level; the climber's RIGHT hand slaps flat onto the packed snow of the ledge, then his knee in dark trousers comes up onto the rock. Contact shadows, snow compressing under the hand. Audio: effortful breathing from both, boots scraping rock, cloth stretching, the hand slapping snow, a grunt. $REAL"
F[G]=kf/K5.png; T[G]="First-person POV kneeling on the ledge, looking at Shiva's face in front of him. He breathes slowly, blinks naturally, and gives a small reassuring nod; wind moves individual strands of his matted hair and the cloth, snow settling on his shoulders. After a few seconds, once the climber is steady, he gently loosens and releases the climber's LEFT wrist and draws his RIGHT hand back. The storm is beginning to calm. Audio: wind softening, the climber's breathing slowing, the soft rustle of cloth. $REAL"
F[H]=kf/K6.png; T[H]="First-person POV kneeling on the ledge with hands folded in namaste in the foreground. Shiva, standing on the same ledge in front, holds his RIGHT hand raised in a gentle blessing, the trident steady in his LEFT hand; he breathes and blinks naturally, a faint calm smile. Very slowly the storm softens: snowfall thins, cloud drifts apart behind him and the snow peak emerges in warm light. Minimal, steady camera with subtle breathing movement, peaceful final composition. Audio: wind dying down to a gentle breeze, a distant temple bell. $REAL"
for id in ${@:-A B C D E G H}; do
  python3 tools/veo2.py "clips/$id.mp4" "${F[$id]}" "${T[$id]}" ${L[$id]:+"${L[$id]}"} > "clips/$id.log" 2>&1 &
  sleep 8
done
wait
for id in ${@:-A B C D E G H}; do echo "$id: $(tail -1 clips/$id.log)"; done
