#!/usr/bin/env bash
cd "$(dirname "$0")/.."
POV="Handheld first-person POV, the camera is the devotee's eyes; keep his forearms, rudraksha bracelet and red thread consistent. Photoreal, cinematic, no text."
v(){ python3 tools/veo.py "clips/$1.mp4" "kf/$1.png" "$2" > "clips/$1.log" 2>&1 & }
v s1 "$POV He climbs hand over hand up the icy rock face in a violent blizzard, breath fogging, snow lashing sideways; the camera tilts up to the golden peak of Mount Kailash glowing through the storm as lightning flickers inside the clouds. Audio: howling wind, heavy breathing, ice crunching under his grip, distant thunder. No music, no speech."
v s2 "$POV His hand grabs the ice ledge, it cracks and breaks away; he looks up as a massive avalanche thunders down the mountain straight toward the camera, a white wall filling the frame. Audio: deep cracking ice, a building avalanche roar, a sharp gasp. No music, no speech."
v s3 "$POV He falls backward into the white-out, arms reaching up, snow and ice tumbling past, the sky spinning and receding, everything fading to white then darker. Audio: rushing roar of the avalanche, wind whoosh, muffled heartbeat. No music, no speech."
v s4 "$POV Silence and darkness deep in an icy chasm, his hand slowly reaches up toward a faint circle of pale light far above, snowflakes drift down in slow motion, his fingers tremble. Very slow subtle camera drift. Audio: near silence, slow heartbeat, faint wind far above. No music, no speech."
v s5 "$POV A powerful ash-blue divine hand with a rudraksha band grips his wrist firmly from above; golden-white light blooms and floods outward, snowflakes glow like sparks, he is pulled upward toward the light. Audio: a deep resonant temple bell and a swelling shimmer, heartbeat stops. No music, no speech."
v s6 "$POV Looking up at Lord Shiva on the cliff edge in the blizzard, he holds the devotee's wrist and pulls him up with calm strength, his gaze compassionate, third eye softly glowing, crescent moon shining, lightning behind him, the cobra stirs. Slight upward camera move as he is lifted. Keep Shiva's face stable. Audio: wind, thunder, the low resonant hum of Om, a damru rattle. No music, no speech."
v s7 "Over-the-shoulder from behind the devotee: Lord Shiva walks ahead along the snowy knife-edge ridge, leading the devotee by the hand toward the glowing golden peak of Mount Kailash; the storm clouds part and green aurora ribbons begin to appear. Smooth steady forward tracking. Audio: crunching footsteps in snow, wind calming, a distant conch shell. No music, no speech. Photoreal, cinematic, no text."
v s8 "Slow epic push-in toward the two small silhouettes of Lord Shiva with his trishul and the devotee walking hand in hand along the snowy ridge toward Mount Kailash glowing gold, the vast emerald and violet aurora shaped like the Om symbol shimmering and flowing across the starry sky. Audio: gentle wind, a single deep conch and a soft Om chant swell. No speech. Photoreal, cinematic, no text."
wait
for f in clips/*.log; do echo "== $f"; tail -1 "$f"; done
